spring:
  application:
    name: EUREKA-HA
server:
  port: 8761
spring:
  profiles: peer2
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer3:8761/eureka/
